app_id: "c4bcfd78-97b3-4922-9577-55ad3d882650"
app_secret: "fureeYKD51676$%izAJWZ-@"
#redirect: "https://explore.auditech.xyz/callback"
redirect: "http://localhost:8000/callback"
scopes: "openid profile offline_access user.read Directory.Read.All calendars.read"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"
