app_id: "52661a60-64fe-4517-9f3f-998e24123604"
app_secret: "GiyQ9._eE2i0Cr1~O0SHzc2dyj_RYD1_K7"
#redirect: "https://explore.auditech.xyz/callback"
redirect: "http://localhost:8000/callback"
scopes: "openid profile offline_access user.read Directory.Read.All calendars.read"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"
